### ISSUE TITLE
Sounds Won't Play & Window Won't Resize

### ISSUE THREAD

**Issue by c4181** [MGraefe/RP-Soundboard#63]
I was using the soundboard without issue on the latest version of TeamSpeak up until last month. I formatted my SSD and did a reinstall of windows. I reinstalled Teamspeak and the soundboard and it hasn't been working since.

I've seen others who experienced this issue deleted the config files and reinstalled Teamspeak. I've also tried this and it hasn't fixed the issue. 

The soundboard doesn't play any files I insert and the window refused to resize. The GIF below shows what happens when trying to resize the window.

[![Screenshot from Gyazo](https://gyazo.com/49f07e2679c77d53edb464b0919e1cdf/raw)](https://gyazo.com/49f07e2679c77d53edb464b0919e1cdf)

**Comment by mwoelke** [comment]
I have the same problem. Hotkeys work for me though, so I guess it's a GUI problem.

I'm using Teamspeak 3.1.9 (Qt Version 5.6.2) and the newest soundboard version.

**Comment by MGraefe** [comment]
@c4181 what version of Teamspeak 3 are you using?
@mwoelke The current version of Teamspeak 3 is 3.2.2, could you please update to that and tell me if the problem still persists?

**Comment by mwoelke** [comment]
@MGraefe Yes, the bug still persists on the newest version.

**Comment by MAKSSOUW** [comment]
I have the same problem, i can't play sound and i can't resize the widow.
I have the last RP Soundboard version and a new Teamspeak3 installation.

OS version: Windows 10 1803
TS version: 3.2.3

Thanks, i love u

**Comment by SFSScorpio** [comment]
I contacted him a few days ago, see issue #68 , it's in german though. He said he's investigating.

**Comment by SFSScorpio** [comment]
@c4181 @mwoelke Solution posted by @MAKSSOUW in issue #68 :

> Hello guy, I have a solution to solve the problem !!
You just have to reset the configuration of the shortcuts for the configs on NONE, because in fact, the problem comes from there! In fact, the hotkey is set to left click, which cancels the launch of a 
soundboard every time!

What he's saying is that in the TS Hotkey settings there is "MOUSE BUTTON 1" set to load config 1 of the soundboard, everytime you pless LMB and let go it resets to Config 1, that's also why resizing doesn't work.
Go to Extras -> Options ->Hotkeys, look for something with "MOUSE BUTTON 1" and delete it, this resolved the issue for me.
Thanks @MAKSSOUW !

**Comment by MGraefe** [comment]
Thanks @MAKSSOUW for finding the solution finally why left clicking on buttons doesn't work. A hotkey bound to mouse 1 makes perfect sense. I will see what I can do to fix or mitigate the issue next week when I have some time off as my fulltime job keeps me quite busy these days. That's also the reason why the development of the sounboard slowed somewhat, after sitting in front of code all day I simply don't have enough motivation left on the evening to do the same thing but without payment :D
