### ISSUE TITLE
TeamSpeak 3 Client 3.1

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [MGraefe/RP-Soundboard#7]
TS3 Beta seems to come with a new API version (and soon, a kind of "store" I think), could you take a look?
The forum announce: http://forum.teamspeak.com/threads/126583-Beta-Channel-TeamSpeak-3-Client-3-1?p=434305#post434305

**Comment by MGraefe** [comment]
Thanks for the notice, I just finished upgrading my Plugin to the new API version. It took a while because I had to update the Qt Version as well as the FFMPEG Build and I also switched to Visual Studio 2015 instead of 2012.
As the new version doesn't start with the old plugin version and the old version doesnt start with the new plugin version I have no way of updating the plugin through the built in updater, people will have to download and install the new version manually..
