### ISSUE TITLE
Support teamspeak 3.1 (Api version 21)

### ISSUE THREAD

**Issue by SergiX44** [MGraefe/RP-Soundboard#8]
This is not working on the new beta version of teamspeak due to different api level.

**Comment by MGraefe** [comment]
My internal version is already working with 3.1, although the latest beta (of Teamspeak) has a show-stopping bug that results in distorted outgoing sound. I am waiting until this is fixed by the devs. The new version would also be exclusively compatible with 3.1, backwards compability isn't possible due to a change in the Qt and Compiler version. That also implies that I cannot update the Plugin through the internal updater when 3.1 hits stable, instead everyone has to download the new version by hand.

**Comment by BobDaBilda** [comment]
Is this still bugged? I'd like to use this with the latest Beta, as I test on the Beta version.

**Comment by MGraefe** [comment]
Yeah it's still broken

**Comment by MGraefe** [comment]
New beta version for Teamspeak 3.1 has been released: http://forum.teamspeak.com/threads/125318-RELEASE-RP-Soundboard
